### ISSUE TITLE
Ebook-viewer, AppimageHub, 6.11

### ISSUE THREAD

**Issue by icetbr** [KushagraKarira/calibre-appimage#1]
Hi there, would you consider
- allow to run ebook-viewer from cmd, see https://discourse.appimage.org/t/call-alternative-binary-from-appimage/93/19
- upload to https://www.appimagehub.com/
- update to 6.11 

Thanks for your efforts to bring Calibre to AppImage!

**Comment by KushagraKarira** [comment]
- Will work on CMD
- Someone already has uploaded on appimagehub : https://www.pling.com/p/1513670/, not sure how any other user can upload
- Released : https://github.com/KushagraKarira/calibre-appimage/releases/tag/6.11.0

**Comment by KushagraKarira** [comment]
re-uploaded at https://www.pling.com/p/1974121/
